### ISSUE TITLE
Sampling to get the training set (180 images)

### ISSUE THREAD

**Issue by jmwang0117** [Harry-Zhi/semantic_nerf#16]
![QQ截图20220808231406](https://user-images.githubusercontent.com/51500826/183451859-5a366fe4-8a00-43a6-9bd4-b08011545959.jpg)
Where can I find code related to this part of the description? （Sampling 180 images as training set）

**Comment by Harry-Zhi** [comment]
Hi @jmwang0117 ,

The whole trajectories (900 images) of Replica sequences all purely randomly generated so that you can see that there are some dramastic motions or occluded views in the training data. For purposes such as SLAM, probably it woule be better to have a smoother camera motion.

To reduce the amount of trainning data, we apply a even sampling to get evety 5th image from the complete sequence (900 images) to generate final 180 images.
