### ISSUE TITLE
Mesh file 

### ISSUE THREAD

**Issue by tensarflow** [Harry-Zhi/semantic_nerf#23]
Hi, i want to test semantic_nerf model, but is extract colour mesh file for testing. If it is, why neccessary mesh file,  is nerf model need to generate mesh model. In conclusion, how can i do testing

**Comment by Harry-Zhi** [comment]
Hi @Harry-Zhi 
Sorry for the late reply due to recent DDL.

3D mesh reconstruction in [extract_colour_mesh.py](https://github.com/Harry-Zhi/semantic_nerf/blob/main/SSR/extract_colour_mesh.py) is used to extract an explicit 3D model out of neural fieds which is less intuitive to inspect by us what geometry has been learned within the MLP model. If you aim to test geometry quality, this may be related. But please note that there is several parameters which affects this process, such as the threshold of marching cubes, the near/far and camera positions during vertex label rendering.

As to quantitaitve  evaluation in 2D image spaces, you could render novel images/depths/labels at certain view points and then use 2D metrics, which origial NeRF and this repo both do, e.g., [depth metrics](https://github.com/Harry-Zhi/semantic_nerf/blob/2608d2fdb66137e08b34b02864e56dd866b877f0/SSR/training/trainer.py#L1032)

**Comment by Harry-Zhi** [comment]
Close it for now. Feel free to re-open it if you have any further questions.
