### ISSUE TITLE
Some result confuse

### ISSUE THREAD

**Issue by zwy020450** [Harry-Zhi/semantic_nerf#3]
Thanks for your publish code! When I test the result in replica, I found that the black area(void label) can't not be perfertly rendered. Could I konw  the reason?
![image](https://user-images.githubusercontent.com/62002491/154960250-c1691f1b-1c91-49fa-a3bb-14c98b3bb4ba.png)

**Comment by Harry-Zhi** [comment]
Hi @zwy020450,
Good to see the results you've got.

About the less satisfying results on the void regions, following the standard practice in semantic segmentation, we **do not** apply any loss on the void regions hence the network is able to predict arbitrary classes without penalty (though in fact it tend to predict some reasonable classes based on the similarity in appearance or geometry). And the void region also does not contribute to the evaluation metrics. Therefore your given result is expected. 

I stick to this set-up in all the experiments of this paper. During visualisation, I mask out the void regions in the prediction using masks from GT void class for better visualisation purpose.

However, as a scene-specific representation, you can also make the void region a valid class and apply loss on it, so that the network will predict void class on these specific regions.

**Comment by bowen099** [comment]
Hello, may I ask if it's possible to visualize the void regions instead of masking them during visualization?
