### ISSUE TITLE
CUDA out of memory when using RTX2080-Ti GPU

### ISSUE THREAD

**Issue by zsh2000** [Harry-Zhi/semantic_nerf#4]
Hi,

Thank you for your inspiring work and the code released!

I'm trying running your demo on "room0" of Replica by 

`python3 train_SSR_main.py --config_file /SSR/configs/SSR_room0_config.yaml`

Whenever it comes to validation time, it will not be able to move on and interrupted by "CUDA out of memory". However, I use the same GPU (RTX2080-Ti with 11GB memory) as mentioned in your paper. Also, no matter how much I decrease the numbers "chunk" and "netchunk" in the config file (even decreasing them to 1024*1), this "CUDA out of memory" would happen during validation time.

I'm wondering whether you could give me some advice.

**Comment by Harry-Zhi** [comment]
HI @zsh2000,

As to training of Semantic-NeRF, a single 2080-Ti with 11GB is indeed affordable. The OOM happens due to the line here as I render all the pixels of all images at once: https://github.com/Harry-Zhi/semantic_nerf/blob/fcdd3c69550be5de60a4cc55be13f5f296ab82f9/SSR/training/trainer.py#L1156. 

You have two-options to avoid the OOM to see what the renderings are:
(1) You can change the *test_viz_factor* in config file to 2 or other larger values so that the rendered images will be at lower resolution compared to that of input ones, which is good enough for visualisation purposes of the training process.

(2) You can also take the strategy used here https://github.com/Harry-Zhi/semantic_nerf/blob/fcdd3c69550be5de60a4cc55be13f5f296ab82f9/SSR/extract_colour_mesh.py#L28 to replace the above mentioned render fn. Specifically, we render all the rays from a single image chunk by chunk and move the rendered values to cpu at the same time to avoid OOM.

I used the first option during training to speed up the overall training process. But if you want to calculate the strict semantic metrics during training, option 2 should be chosen.

Hope it helps!

**Comment by zsh2000** [comment]
Thanks for your advice! I'll have a try.
